### ISSUE TITLE
`cargo install` able CLI version

### ISSUE THREAD

**Issue by HKalbasi** [vi/syn-file-expand#1]
Downloading release binaries in CI is a bit hard, is it possible to make it a binary crate instead of a file in `example` directory so it will become installable via `cargo install synfileexpand`?

**Comment by vi** [comment]
Just `cargo install syn-file-expand --example expand`? Shall I put that in README?

Or maybe the CLI tool warrants being a separate crate (not just a demo of the library), with a proper arguments parsing?

**Comment by HKalbasi** [comment]
Ah, didn't know that examples are installable as well, TIL!

> Or maybe the CLI tool warrants being a separate crate (not just a demo of the library), with a proper arguments parsing?

Current state satisfies me, just it would be nice to rename the example to something more detailed (`syn-file-expand-cli`?) because it currently names the executable as `expand` by default.

**Comment by vi** [comment]
I was also wondering if `expand` is a good name (and within the example itself it is named as `synfileexpand`), but though that `synfile*` would look redundant within the `syn-file-expand/examples/` directory.

Maybe I should just publish `syn-file-expand-cli` crate, dedicated to the tool (maybe even adding e.g. `loop{}`-ificator).

**Comment by HKalbasi** [comment]
It is good as is, and the binary name doesn't really matter.

I'm using this to pack std library to some single file and send it to browser for rust analyzer wasm. `loop {}`ification helps in reducing bandwidth usage and parsing time in the client (which is around 8s, not really great), but it is an unrelated problem to this crate. My current ad hoc parser isn't loopify anyway, and it doesn't consider `cfg` while this tool does, which is reducing core size from 12.2 mg to 3.1 mg (thank you!).

I'm going to close this issue since the cli is already `cargo install`able.
